/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bully.h"


void
bully_pgm_1(char *host)
{
	CLIENT *clnt;
	OUTPUT  *result_1;
	INPUT  leaderelection_1_arg;
	void  *result_2;
	INPUT  alivemessage_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BULLY_PGM, BULLY_PGM_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = leaderelection_1(&leaderelection_1_arg, clnt);
	if (result_1 == (OUTPUT *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = alivemessage_1(&alivemessage_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bully_pgm_1 (host);
exit (0);
}
