/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BULLY_H_RPCGEN
#define _BULLY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct INPUT {
	char *srcIP;
	char *destIP;
	int srcId;
	int destId;
};
typedef struct INPUT INPUT;

struct OUTPUT {
	char *srcIP;
	char *destIP;
	int srcId;
	int destId;
};
typedef struct OUTPUT OUTPUT;

#define BULLY_PGM 0x23451101
#define BULLY_PGM_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define leaderElection 1
extern  OUTPUT * leaderelection_1(INPUT *, CLIENT *);
extern  OUTPUT * leaderelection_1_svc(INPUT *, struct svc_req *);
#define aliveMessage 2
extern  void * alivemessage_1(INPUT *, CLIENT *);
extern  void * alivemessage_1_svc(INPUT *, struct svc_req *);
extern int bully_pgm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leaderElection 1
extern  OUTPUT * leaderelection_1();
extern  OUTPUT * leaderelection_1_svc();
#define aliveMessage 2
extern  void * alivemessage_1();
extern  void * alivemessage_1_svc();
extern int bully_pgm_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_INPUT (XDR *, INPUT*);
extern  bool_t xdr_OUTPUT (XDR *, OUTPUT*);

#else /* K&R C */
extern bool_t xdr_INPUT ();
extern bool_t xdr_OUTPUT ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BULLY_H_RPCGEN */
