/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bully.h"

OUTPUT *
leaderelection_1_svc(INPUT *argp, struct svc_req *rqstp)
{
	static OUTPUT  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
alivemessage_1_svc(INPUT *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
