/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bully.h"

bool_t
xdr_INPUT (XDR *xdrs, INPUT *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->srcIP, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->destIP, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->srcId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->destId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OUTPUT (XDR *xdrs, OUTPUT *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->srcIP, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->destIP, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->srcId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->destId))
		 return FALSE;
	return TRUE;
}
